config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  post '/toppage/guest_sign_in', to: 'toppages#new_guest'

  get 'relationships/create'
  get 'relationships/destroy'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :users, only: %i[index show create edit update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]

  end

  resources :reels, only: %i[show new create destroy edit update]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :post_category, only: %i[index show create]
end

app/models/user.rb
class User < ApplicationRecord
  # バリデーション
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :introduction, presence: false, length: { maximum: 200 }
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :reels, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user

  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :post

  has_many :comments, dependent: :destroy

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def like(post)
    favorites.find_or_create_by(post_id: post.id) unless self == post
  end

  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

  def like?(post)
    likes.include?(post)
  end

  def feed_posts
    Post.where(user_id: following_ids + [id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: %i[index show edit followings followers likes]
  before_action :user_find, only: [:followings, :followers, :likes]


  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])

    @posts = @user.posts.order(id: :desc).page(params[:page]).per(6)
    counts(@user)

    @reels = @user.reels.order(id: :desc).page(params[:page]).per(6)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])

    redirect_to current_user unless @user == current_user
  end

  def update
    @user = User.find(params[:id])

    if current_user == @user
      if @user.update(user_params)
        flash[:success] = '正常に更新されました'
        redirect_to current_user
      else
        flash.now[:danger] = '更新に失敗しました'
        render :edit
      end
    else
      redirect_to current_user
    end
  end

  def followings
    # @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end

  def followers
    # @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  def likes
    # @user = User.favorites.find(:micropost)
    # @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :avatar, :avatar_cache)
  end

  def user_find
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<div class="users_list">
  <% if users.any? %>
    <ul class="user_list">
      <% users.each do |user| %>
        <li class="user_list_icon">
          <% if user.avatar? %>
            <%=link_to image_tag(user.avatar_url, class: "user_icon"),user_path(user) %>
          <% else %>
            <%=link_to image_tag "/assets/default-avatar.png", :size => "132x132", class: "mr-2 rounded" %>
          <% end %>

          <div class="user_list_text">
            <div>
              <p><%=link_to user.name, user_path(user) %></p>
            </div>
          </div>

        </li>
      <% end %>
    </ul>
    <%= paginate users %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="user_edit_page">
    <!--エラーメッセージ-->
  <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
  <% end %>
    

  <div class="form_all">
      <%= form_with(model: @user, local: true) do |f| %>
      
        <div>
          <h2>Profile</h2>
        </div>
<%# 画像 %>
        <%= image_tag @user.avatar_url if @user.avatar? %>
        <div class="form_block center-block">
          <%= f.file_field :avatar%><br>
        </div>
        <%= f.hidden_field :avatar_cache %>
          
<%# 名前  %>
        <div class="form_block">
          <%= f.label :name, "Name" %><br>
          <%= f.text_field :name, class: "form", placeholder: "お名前" %>
        </div>

<%# 自己紹介 %>
        <div class="form_block">
          <%= f.label :introduction, "Introduction" %><br>
          <%= f.text_area :introduction, size: "80x6" ,placeholder: "自己紹介"%>
        </div>
          

        <div class="form_block">
          <%= f.label :email, "Email" %><br>
          <%= f.email_field :email, class: "form", placeholder: "Email"  %>
        </div>
  
        <div class="form_block">
          <%= f.label :password, "Password" %><br>
          <%= f.password_field :password, class: "form"  %>
        </div>
  
        <div class="form_block">
          <%= f.label :password_confirmation, "Password_confirmation" %><br>
          <%= f.password_field :password_confirmation, class: "form" %>
        </div>
  
        <%= f.submit 'Save', class: 'btn' %>
      
    <% end %>
  </div>    
</div>

app/views/users/followers.html.erb
<div class="user_index">
  <%= render 'users', users: @followers %>
</div>  

app/views/users/followings.html.erb
<div class="user_index">
  <%= render 'users', users: @followings %>
</div>
  

app/views/users/index.html.erb
<div class="user_index">
  <%= render 'users', users: @users %>
</div>

app/views/users/likes.html.erb
<div class="user_index">
    <%= render 'posts/posts', posts: @likes %>
</div>

app/views/users/new.html.erb
  <!--エラーメッセージ-->
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
<% end %>

<div class="user_new">
  <div class="text-center">
    <h1>REGISTER</h1>
  </div>   
      
  <div class="row center-block">
    <div class="col-sm-6 offset-sm-3">
      
      
      <%= form_with(model: @user, local: true) do |f| %>
      
        <div class="form-group">
          <%= f.label :name, 'Name' %><br>
          <%= f.text_field :name, class: 'form', placeholder: "Akira Tanaka" %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'Email' %><br>
          <%= f.email_field :email, class: 'form', placeholder: "akira@mail.com"%>
        </div>

        <div class="form-group">
          <%= f.label :password, 'Password' %><br>
          <%= f.password_field :password, class: 'form' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %><br>
          <%= f.password_field :password_confirmation, class: 'form' %>
        </div>

        <%= f.submit 'REGISTER', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
    <div class="user_show">
        <div class="user_info">
            <div class="user_info_left">   
                <% if @user.avatar? %>
                <div class="user_icon">
                    <%= image_tag @user.avatar_url, class: "user_icon"%>
                </div>    
                <% else %>
                    <%= image_tag "/assets/default-avatar.png", class: "user_icon" %>
                 <% end %>  
            </div>
            
            <div class="user_info_right">
              <div class="user_name_edit">
                <h1><%= @user.name %></h1>
               <% if @user == current_user %>
                 <div class="user_edit">
                  <%= link_to "Edit profile", "/users/#{@user.id}/edit", class: 'btn btn-default' %>
                  </div>
               <% else %>
                 <dvi></dvi>
               <% end %>
       
              </div>
                <p><%= @user.introduction %></p>
                <p><%#= safe_join(@user.introduction.split("\n"),tag(:br)) %></p>
              <div class="relationships_btn">    
             
                    <div class="relationships_btn_all">
                        <div>
                            <a href="<%= followings_user_path(@user) %>">Following</a>
                        </div>
                        <div>
                            <a href="<%= followings_user_path(@user) %>"><%= @count_followings %></a>
                        </div>
                    </div>
                    
                    <div class="relationships_btn_all">
                        <div>
                            <a href="<%= followers_user_path(@user) %>">Followers</a>
                        </div>
                        <div>
                            <a href="<%= followers_user_path(@user) %>"><%= @count_followers %></a>
                        </div>
                    </div>
                    
                    <div class="relationships_btn_all">
                        <div>
                           <a href="<%= likes_user_path(@user) %>">likes</a>
                        </div>
                        <div>
                            <a href="<%= likes_user_path(@user) %>"><%= @count_likes %></a>
                        </div>
                    </div>
              </div>    
            </div>  
        </div>
    </div>   

    
    <% if @user == current_user %>
        <div class="btn_all">
            <div class="post_btn">
                <%= link_to "SUBMIT YOUR SKIL", "/posts/new", class: 'btn post_reel' %>
            </div>

             <div class="reel_btn">
                <%= link_to "SUBMIT YOUR REEL", "/reels/new", class: 'btn reel_btn' %>
            </div>
            
        </div> 
           
    <% else %>
        <div class="btn_all">
            <div class="follow_btn">
                <%= render 'relationships/follow_button', user: @user, class: 'btn' %>    
            </div>
        </div>    
    <% end %>

    <div class="user_reel">
        <%= render "reels/reels", reels:@reels %>
    </div>
    <div class="user_post">
        <%= render "posts/posts", posts:@posts %>      
    </div>

    
    
</div>    