config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  post '/toppage/guest_sign_in', to: 'toppages#new_guest'

  get 'relationships/create'
  get 'relationships/destroy'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :users, only: %i[index show create edit update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]

  end

  resources :reels, only: %i[show new create destroy edit update]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :post_category, only: %i[index show create]
end

app/models/reel.rb
class Reel < ApplicationRecord
  belongs_to :user
end

app/controllers/reels_controller.rb
class ReelsController < ApplicationController
  before_action :require_user_logged_in, only: %i[new create destory edit update]
  before_action :corrent_user, only: [:destroy]

  def show
    @reel = Reel.find(params[:id])
  end

  def new
    @reel = current_user.reels.build
  end

  def create
    @reel = current_user.reels.build(reel_params)

    url = params[:reel][:youtube_url]
    # url = url.last(11)
    @reel.youtube_url = url

    if @reel.save
      flash[:success] = '投稿しました。'
      redirect_to current_user
    else
      @reels = current_user.feed_reels.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'リールの投稿に失敗しました。'
      redirect_to current_user
    end
  end

  def destroy
    @reel.destroy
    flash[:success] = '削除しました。'
    redirect_to current_user
  end

  def edit
    @reel = Reel.find_by(id: params[:id])
  end

  def update
    @reel = Reel.find_by(id: params[:id])

    if @reel.update(reel_params)
      flash[:success] = '更新しました'
      redirect_to @reel

    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  private

  def reel_params
    params.require(:reel).permit(:youtube_url)
  end

  def corrent_user
    @reel = current_user.reels.find_by(id: params[:id])
    redirect_to current_user unless @reel
  end
end

app/helpers/reels_helper.rb
module ReelsHelper
end

app/views/reels/_reels.html.erb
<%# if reels.present? %>
<div class="reel">

<%# <p>Showreel</p> %>

	<% reels.each do |reel| %>

			<div class="col-md-3">
				<div class="reel_content">
					<iframe width="416" height="234" src="https://www.youtube.com/embed/<%= reel.youtube_url[32..42]%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				</div>	
							<% if current_user == reel.user %>
									<%# <div class="reel_delete"> %>
										<%= link_to "×", reel, method: :delete, data: { confirm: "You sure?" }, class: 'btn_delete' %>
									<%# </div> %>
							<% else %>
									<div class="reel_show_list">
										<%= link_to ">", reel_path(reel.id), class: 'btn_show' %>
									</div>		
							<% end %> 
				
			</div>

								
	<% end %>


<div class="posts_paginate">  
      <%= paginate reels %>
</div>   

</div>

app/views/reels/edit.html.erb
<%# <div class="row">
  <div class="col-6">  %>

    <div class="reel_form">
  <%= form_with(model: @reel, local: true) do |f| %>
    <div class="reel_url">
              <%= f.label :youtube_url, "YouTube",  class:'control-label' %>
              <%= f.text_field :youtube_url, placeholder: 'youtube_url' , class: 'form-control'%>
    </div>

    <div class="reel_post">
    <%= f.submit 'POST', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
    </div>

  <%# </div>
</div> %>

app/views/reels/new.html.erb
<%# <div class="row">
  <div class="col-6">  %>

    <div class="reel_form">
  <%= form_with(model: @reel, local: true) do |f| %>
    <div class="reel_url">
              <%= f.label :youtube_url, "YouTube",  class:'control-label' %>
              <%= f.text_field :youtube_url, placeholder: 'youtube_url' , class: 'form-control'%>
    </div>

    <div class="reel_post">
    <%= f.submit 'POST', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>
    </div>

  <%# </div>
</div> %>

app/views/reels/show.html.erb
<div class="reel_show_all">
  <div class="reel_show">
  <iframe width="960" height="540" src="https://www.youtube.com/embed/<%= @reel.youtube_url[32..42]%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>