config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  post '/toppage/guest_sign_in', to: 'toppages#new_guest'

  get 'relationships/create'
  get 'relationships/destroy'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'

  resources :users, only: %i[index show create edit update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end

  resources :posts do
    resources :comments, only: %i[create destroy]

  end

  resources :reels, only: %i[show new create destroy edit update]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :post_category, only: %i[index show create]
end

app/views/layouts/_error_messages.html.erb
<div class="error_message">
  <% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="flash_messages">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
</div>  

app/views/layouts/_nav.html.erb
<header>       

    <% if logged_in? %>
     <div class="header_menus_creators">
          <ul>
            <li><%= link_to 'CREATORS', users_path, class: "users_btn"%></li>
          </ul>  
     </div>

      <div class="header_main">
        <div class="header_logo">
          <%= link_to embedded_svg("video_creators.svg", class: "logo_svg"), root_url(current_user) %> 
      </div>

        <ul class="header_menus">
          <li><%= link_to 'MY PAGE', user_path(current_user.id), class:"mypage_btn" %></li>
          <li><%= link_to 'LOGOUT', logout_path, method: :delete, class: "logout" %></li>
        </ul>  
        
      </div>  
    <% else %>
      <div class="header_top">
        <p>For all video creators.</p>
      </div>   
      <div class="header_main">
      <div class="header_logo">
        <%= link_to embedded_svg("video_creators.svg", class: "logo_svg"), "/" %>
      </div>
        <ul class="header_menus">
          <%#= link_to 'REGISTER', signup_path, class: "register" %>
          <li><%= link_to 'LOGIN', login_path, class: "login" %></li>
        </ul>
      </div>  
      
    <% end %>  

  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VIDEO CREATORS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="container">
      <%# <%= render "layouts/flash_messages" %> %>
      
    <%= yield %>
    </div>
  </body>
</html>